dai_portfolio_home:
    path:      /{page}
    defaults:  { _controller: DaiPortfolioBundle:Work:index, page: 1 }
    requirements:
        page: \d*

dai_portfolio_view:
    path:      /work/{id}
    defaults:  { _controller: DaiPortfolioBundle:Work:view }
    requirements:
        id: \d+

dai_portfolio_add:
    path:      /add
    defaults:  { _controller: DaiPortfolioBundle:Work:add }

dai_portfolio_edit:
    path:      /edit/{id}
    defaults:  { _controller: DaiPortfolioBundle:Work:edit }
    requirements:
        id: \d+

dai_portfolio_delete:
    path:      /delete/{id}
    defaults:  { _controller: DaiPortfolioBundle:Work:delete }
    requirements:
        id: \d+
