dai_work_index:
    path:      /{page}
    defaults:  { _controller: DaiPortfolioBundle:Work:index, page: 1 }
    requirements:
        page: \d*

dai_work_add:
    path:      /add
    defaults:  { _controller: DaiPortfolioBundle:Work:add }

dai_work_edit:
    path:      /edit/{id}
    defaults:  { _controller: DaiPortfolioBundle:Work:edit }
    requirements:
        id: \d+

dai_work_delete:
    path:      /delete/{id}
    defaults:  { _controller: DaiPortfolioBundle:Work:delete }
    requirements:
        id: \d+
